import './globals.css'
import type { Metadata } from 'next'
import { Dancing_Script } from 'next/font/google'
import "tw-elements/dist/css/tw-elements.min.css";
import Navbar from './components/Navbar';
import Footer from './components/Footer';


const inter = Dancing_Script({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Explore Moroccan Landscapes',
  description: 'Generated by create next app',
  icons:{
    icon:'/favicon.jpeg'
  } 
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <main className='min-h-[100vh]'>
        {children}
        </main>
        <Footer/>
        </body>
    </html>
  )
}
